### ISSUE TITLE
Implementação  de carrossel na home

### ISSUE THREAD

**Issue by henriqueburgos** [henriqueburgos/souldrinks#9]
Implementar o carrossel usando o ng-bootstrap na pagina home.

LINK DO NG BOOTSTRAP
https://ng-bootstrap.github.io/#/components/carousel/examples 

OBS usar imagens aleatórias , as imagens serão inseridas em outro card.

**Comment by Taisaferreiraflavio** [comment]
carrossel pagina home e instalação bootstrap
